### ISSUE TITLE
Symbol lookup error: GOMP_parallel_sections

### ISSUE THREAD

**Issue by Nelarius** [tjhakkin/MorphoMaker#1]
When running the simulation using the FungiHexa model, the program crashes due to a symbol lookup error:

`./MorphoMaker: symbol lookup error: .../MorphoMaker/build/Resources/bin/libfungihexa.so: undefined symbol: GOMP_parallel_sections`

**Comment by tjhakkin** [comment]
Incorrect use of -fopenmp flags. Fixed.
